### PR TITLE
added landmark row_id to ouput. Improved stability

### PR DESCRIPTION
**Pull request by janstorz**

### CODE REVIEW

**Comment by benoitfrisque** [comment]
Task linked: [CU-86by03dry Create a local API (Uvicorn)](https://app.clickup.com/t/86by03dry)

**Review by benoitfrisque — COMMENTED** [review]
Hey @janstorz , I worked yesterday on the landmarks to have the proper json format.  Could you check my code in my branch? I'm now able to read the full json properly and get a prediction 👍

**Review by benoitfrisque — CHANGES_REQUESTED** [review]
Too many conflicts... Could you try out what I modified first? I think Json structure was not correct in your first version. We can discuss it tomorrow

**Comment by janstorz** [comment]
Yes, I merged the versions and pushed it. It should be just your version now. I think you just have to approve it.

**Pull request closed without merging**
